spring:
  config:
    import: "optional:file:env.properties"
  application:
    name: com.example.api
  profiles:
    active: @spring.profiles.active@
  data:
    mongodb:
      uri: ${MONGO_URI}
      authentication-database: ${AUTHENTICATION_DB:admin}
      auto-index-creation: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none # "none" manage by flyway
    show-sql: true
    open-in-view: false # false open-in-view custom query để lấy data
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  logging:
    level:
    org.hibernate.SQL: debug
    org.flywaydb.core: info
  servlet:
    multipart:
      max-file-size: 5120KB
      max-request-size: 5120KB
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
  app:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
#openapi:
#  service:
#    api-docs: api-service
#    server: http://localhost:8080
#    title: API Service
#    version: 1.0.0
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui
#    operationsSorter: method
#    tagsSorter: alpha