spring:
  config:
    import: "optional:file:env.properties"
  application:
    name: com.example.api
  profiles:
    active: @spring.profiles.active@
  data:
    mongodb:
      uri: ${MONGO_URI}
      authentication-database: ${AUTHENTICATION_DB:admin}
      auto-index-creation: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5120KB
      max-request-size: 5120KB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#openapi:
#  service:
#    api-docs: api-service
#    server: http://localhost:8080
#    title: API Service
#    version: 1.0.0
#
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui
#    operationsSorter: method
#    tagsSorter: alpha